# Generated by Django 5.2.8 on 2025-11-11 12:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_attempt_fields_gameguess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='code',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='Value must be exactly 4 digits.', regex='^\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='game',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='gameguess',
            name='guess',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='Value must be exactly 4 digits.', regex='^\\d{4}$')]),
        ),
    ]
